name: build plugins


on:
  workflow_dispatch:
    inputs: 
      release:
        description: 'release version'
        required: true
        default: 'v1.0.2'
  push:
    paths:
      - 'plugins/**'

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: install deps
        run: pnpm install

      - name: bulild store.json
        run: pnpm run build-store

      - name: deploy store
        run: pnpm run deploy-store

      - uses: actions/upload-artifact@v2
        with:
          name: plugins
          path: "build/store.json"

