name: build plugins


on:
  workflow_dispatch:
    inputs: 
      release:
        description: 'release version'
        required: true
        default: 'v1.0.2'
  push:
    paths:
      - 'remote/**'

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: install pnpm
        run: npm install -g pnpm

      - name: install deps
        run: pnpm install

      - name: to remote path
        run: cd remote

      - name: bulild store.json
        run: pnpm run build-store

      - name: deploy store
        run: pnpm run deploy-store


