name: publish app


on:
  workflow_dispatch:
    inputs: 
      release:
        description: 'release version'
        required: true
        default: 'v1.0.2'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      #todo 运行测试

      - name: import application certificate
        id: keychain
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - run: flutter config --enable-macos-desktop

      # flutter build macos 会自动运行 flutter pub get
      - name: build macos
        run: |
          tag=${{ github.ref_name }}
          version=${tag:1}
          number=`date +%Y%m%d%H%M%S`
          flutter build macos --build-name=$version --build-number=$number

      - name: zip *.app
        run: ditto -c -k --sequesterRsrc --keepParent "build/macos/Build/Products/Release/public tools.app" "build/macos/Build/Products/Release/public tools.zip"

      - name: "Notarize Release Build"
        env:
          AC_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
          AC_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          echo "notarize app"
          notarize_response=`xcrun notarytool submit "build/macos/Build/Products/Release/public tools.zip" --apple-id "$AC_USERNAME" --password "$AC_PASSWORD" --team-id "$TEAM_ID" --wait --progress`
          echo "$notarize_response"

          echo "check status"

          t=`echo "$notarize_response" | grep "status: Accepted"`
          f=`echo "$notarize_response" | grep "Invalid"`
          if [[ "$t" != "" ]]; then
              echo "notarization done!"
              xcrun stapler staple "build/macos/Build/Products/Release/public tools.app"
              echo "stapler done!"
          fi
          if [[ "$f" != "" ]]; then
              echo "notarization failed"
              exit 1
          fi

      - uses: actions/upload-artifact@v2
        with:
          name: build-app
          path: "build/macos/Build/Products/Release/public tools.zip"

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/macos/Build/Products/Release/public tools.zip"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
